export { default as App } from 'pages/App';
export { default as Home } from 'pages/Home';
export { default as Formations } from 'pages/Formations';
export { default as Formation1} from 'pages/Formation1';
export { default as Formation2} from 'pages/Formation2';
export { default as Formation3} from 'pages/Formation3';
export { default as Formation4} from 'pages/Formation4';
export { default as Reseau } from 'pages/Reseau';
export { default as Ludotheque } from 'pages/Ludotheque';
export { default as About} from 'pages/About';
export { default as Contact } from 'pages/Contact';
export { default as Liens } from 'pages/Liens';
export { default as LoginOrRegister} from 'pages/LoginOrRegister';
export { default as ForgotPassword} from 'pages/ForgotPassword';
export { default as ResetPassword} from 'pages/ResetPassword';
export { default as Confirmation} from 'pages/Confirmation';
export { default as Dashboard} from 'pages/Dashboard';
export { default as AccountSettings} from 'pages/AccountSettings';
export { default as AdminNews} from 'pages/AdminNews';
export { default as AdminEvents} from 'pages/AdminEvents';
export { default as AdminUsers} from 'pages/AdminUsers';
export { default as Mentions} from 'pages/Mentions';