export { default as App } from 'pages/App';
export { default as Home } from 'pages/Home';
export { default as Formations } from 'pages/Formations';
export { default as Formation1} from 'pages/Formation1';
export { default as Formation2} from 'pages/Formation2';
export { default as Formation3} from 'pages/Formation3';
export { default as Formation4} from 'pages/Formation4';
export { default as Reseau } from 'pages/Reseau';
export { default as Ludotheque } from 'pages/Ludotheque';
export { default as About} from 'pages/About';
export { default as Contact } from 'pages/Contact';
export { default as Liens } from 'pages/Liens';
export { default as LoginOrRegister} from 'pages/LoginOrRegister';
export { default as ForgotPassword} from 'pages/ForgotPassword';
export { default as ResetPassword} from 'pages/ResetPassword';
export { default as Confirmation} from 'pages/Confirmation';
export { default as Dashboard} from 'pages/admin/Dashboard';
export { default as AccountSettings} from 'pages/admin/AccountSettings';
export { default as PersonalData} from 'pages/admin/PersonalData';
export { default as ContactDetails} from 'pages/admin/ContactDetails';
export { default as LoginDetails} from 'pages/admin/LoginDetails';
export { default as MyToys} from 'pages/admin/MyToys';
export { default as MyToy} from 'pages/admin/MyToy';
export { default as AdminNews} from 'pages/admin/AdminNews';
export { default as AdminEvents} from 'pages/admin/AdminEvents';
export { default as AdminUsers} from 'pages/admin/AdminUsers';
export { default as AdminUser} from 'pages/admin/AdminUser';
export { default as AdminToyLibrary} from 'pages/admin/AdminToyLibrary';
export { default as AdminToy} from 'pages/admin/AdminToy';
export { default as AdminToys} from 'pages/admin/AdminToys';
export { default as AdminToyCategories} from 'pages/admin/AdminToyCategories';
export { default as AdminToyCategory} from 'pages/admin/AdminToyCategory';
export { default as AdminToyTags} from 'pages/admin/AdminToyTags';
export { default as AdminToyTag} from 'pages/admin/AdminToyTag';
export { default as Mentions} from 'pages/Mentions';