export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
export const CONFIRM_SUCCESS_USER = 'CONFIRM_SUCCESS_USER';
export const CONFIRM_ERROR_USER = 'CONFIRM_ERROR_USER';

export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';

export const INIT_RESET_PASSWORD = 'INIT_RESET_PASSWORD';
export const INIT_RESET_PASSWORD_SUCCESS = 'INIT_RESET_PASSWORD_SUCCESS';
export const INIT_RESET_PASSWORD_ERROR = 'INIT_RESET_PASSWORD_ERROR';
export const COMPLETE_RESET_PASSWORD = 'COMPLETE_RESET_PASSWORD';
export const COMPLETE_RESET_PASSWORD_SUCCESS = 'COMPLETE_RESET_PASSWORD_SUCCESS';
export const COMPLETE_RESET_PASSWORD_ERROR = 'COMPLETE_RESET_PASSWORD_ERROR';

export const UPDATE_PERSONAL_DATA = 'UPDATE_PERSONAL_DATA';
export const UPDATE_PERSONAL_DATA_SUCCESS = 'UPDATE_PERSONAL_DATA_SUCCESS';
export const UPDATE_PERSONAL_DATA_ERROR = 'UPDATE_PERSONAL_DATA_ERROR';

export const UPDATE_CONTACT_DETAILS = 'UPDATE_CONTACT_DETAILS';
export const UPDATE_CONTACT_DETAILS_SUCCESS = 'UPDATE_CONTACT_DETAILS_SUCCESS';
export const UPDATE_CONTACT_DETAILS_ERROR = 'UPDATE_CONTACT_DETAILS_ERROR';

export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_EMAIL_SUCCESS = 'UPDATE_EMAIL_SUCCESS';
export const UPDATE_EMAIL_ERROR = 'UPDATE_EMAIL_ERROR';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const ADMIN_USER_SAVE = 'ADMIN_USER_SAVE';
export const ADMIN_USER_CREATE_SUCCESS = 'ADMIN_USER_CREATE_SUCCESS';
export const ADMIN_USER_UPDATE_SUCCESS = 'ADMIN_USER_UPDATE_SUCCESS';
export const ADMIN_USER_SAVE_ERROR = 'ADMIN_USER_SAVE_ERROR';

export const ADMIN_USER_DELETE = 'ADMIN_USER_DELETE';
export const ADMIN_USER_DELETE_SUCCESS = 'ADMIN_USER_DELETE_SUCCESS';
export const ADMIN_USER_DELETE_ERROR = 'ADMIN_USER_DELETE_ERROR';

export const ADMIN_TOY_SAVE = 'ADMIN_TOY_SAVE';
export const ADMIN_TOY_CREATE_SUCCESS = 'ADMIN_TOY_CREATE_SUCCESS';
export const ADMIN_TOY_UPDATE_SUCCESS = 'ADMIN_TOY_UPDATE_SUCCESS';
export const ADMIN_TOY_SAVE_ERROR = 'ADMIN_TOY_SAVE_ERROR';

export const ADMIN_TOY_CAT_SAVE = 'ADMIN_TOY_CAT_SAVE';
export const ADMIN_TOY_CAT_CREATE_SUCCESS = 'ADMIN_TOY_CAT_CREATE_SUCCESS';
export const ADMIN_TOY_CAT_UPDATE_SUCCESS = 'ADMIN_TOY_CAT_UPDATE_SUCCESS';
export const ADMIN_TOY_CAT_DUPLICATE = 'ADMIN_TOY_CAT_DUPLICATE';
export const ADMIN_TOY_CAT_SAVE_ERROR = 'ADMIN_TOY_CAT_SAVE_ERROR';

export const ADMIN_TOY_CAT_DELETE = 'ADMIN_TOY_CAT_DELETE';
export const ADMIN_TOY_CAT_DELETE_SUCCESS = 'ADMIN_TOY_CAT_DELETE_SUCCESS';
export const ADMIN_TOY_CAT_DELETE_ERROR = 'ADMIN_TOY_CAT_DELETE_ERROR';

export const ADMIN_TOY_TAG_SAVE = 'ADMIN_TOY_TAG_SAVE';
export const ADMIN_TOY_TAG_CREATE_SUCCESS = 'ADMIN_TOY_TAG_CREATE_SUCCESS';
export const ADMIN_TOY_TAG_UPDATE_SUCCESS = 'ADMIN_TOY_TAG_UPDATE_SUCCESS';
export const ADMIN_TOY_TAG_DUPLICATE = 'ADMIN_TOY_TAG_DUPLICATE';
export const ADMIN_TOY_TAG_SAVE_ERROR = 'ADMIN_TOY_TAG_SAVE_ERROR';

export const ADMIN_TOY_TAG_DELETE = 'ADMIN_TOY_TAG_DELETE';
export const ADMIN_TOY_TAG_DELETE_SUCCESS = 'ADMIN_TOY_TAG_DELETE_SUCCESS';
export const ADMIN_TOY_TAG_DELETE_ERROR = 'ADMIN_TOY_TAG_DELETE_ERROR';

export const ADMIN_TOY_LIB_SAVE = 'ADMIN_TOY_LIB_SAVE';
export const ADMIN_TOY_LIB_CREATE_SUCCESS = 'ADMIN_TOY_LIB_CREATE_SUCCESS';
export const ADMIN_TOY_LIB_UPDATE_SUCCESS = 'ADMIN_TOY_LIB_UPDATE_SUCCESS';
export const ADMIN_TOY_LIB_SAVE_ERROR = 'ADMIN_TOY_LIB_SAVE_ERROR';

export const ADMIN_TOY_LIB_DELETE = 'ADMIN_TOY_LIB_DELETE';
export const ADMIN_TOY_LIB_DELETE_SUCCESS = 'ADMIN_TOY_LIB_DELETE_SUCCESS';
export const ADMIN_TOY_LIB_DELETE_ERROR = 'ADMIN_TOY_LIB_DELETE_ERROR';

export const TOY_SAVE = 'TOY_SAVE';
export const TOY_CREATE_SUCCESS = 'TOY_CREATE_SUCCESS';
export const TOY_UPDATE_SUCCESS = 'TOY_UPDATE_SUCCESS';
export const TOY_SAVE_ERROR = 'TOY_SAVE_ERROR';

export const TOY_DELETE = 'TOY_DELETE';
export const TOY_DELETE_SUCCESS = 'TOY_DELETE_SUCCESS';
export const TOY_DELETE_ERROR = 'TOY_DELETE_ERROR';

export const EXPAND_FILTER = 'EXPAND_FILTER';
export const COLLAPSE_FILTER = 'COLLAPSE_FILTER';

export const ADD_CAT_IN_FILTER = 'ADD_CAT_IN_FILTER';
export const REMOVE_CAT_FROM_FILTER = 'REMOVE_CAT_FROM_FILTER';

export const ADD_TAG_IN_FILTER = 'ADD_TAG_IN_FILTER';
export const REMOVE_TAG_FROM_FILTER = 'REMOVE_TAG_FROM_FILTER';

export const TOY_SEARCH = 'TOY_SEARCH';
export const TOY_SEARCH_SUCCESS = 'TOY_SEARCH_SUCCESS';
export const TOY_SEARCH_ERROR = 'TOY_SEARCH_ERROR';