export const DISMISS_MESSAGE = 'DISMISS_MESSAGE';

export const CREATE_REQUEST = 'CREATE_REQUEST';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const TOGGLE_LOGIN_MODE = 'TOGGLE_LOGIN_MODE';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
export const CONFIRM_SUCCESS_USER = 'CONFIRM_SUCCESS_USER';
export const CONFIRM_ERROR_USER = 'CONFIRM_ERROR_USER';

export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';

export const INIT_RESET_PASSWORD = 'INIT_RESET_PASSWORD';
export const INIT_RESET_PASSWORD_SUCCESS = 'INIT_RESET_PASSWORD_SUCCESS';
export const INIT_RESET_PASSWORD_ERROR = 'INIT_RESET_PASSWORD_ERROR';
export const COMPLETE_RESET_PASSWORD = 'COMPLETE_RESET_PASSWORD';
export const COMPLETE_RESET_PASSWORD_SUCCESS = 'COMPLETE_RESET_PASSWORD_SUCCESS';
export const COMPLETE_RESET_PASSWORD_ERROR = 'COMPLETE_RESET_PASSWORD_ERROR';

export const UPDATE_PERSONAL_DATA = 'UPDATE_PERSONAL_DATA';
export const UPDATE_PERSONAL_DATA_SUCCESS = 'UPDATE_PERSONAL_DATA_SUCCESS';
export const UPDATE_PERSONAL_DATA_ERROR = 'UPDATE_PERSONAL_DATA_ERROR';

export const UPDATE_CONTACT_DETAILS = 'UPDATE_CONTACT_DETAILS';
export const UPDATE_CONTACT_DETAILS_SUCCESS = 'UPDATE_CONTACT_DETAILS_SUCCESS';
export const UPDATE_CONTACT_DETAILS_ERROR = 'UPDATE_CONTACT_DETAILS_ERROR';

export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_EMAIL_SUCCESS = 'UPDATE_EMAIL_SUCCESS';
export const UPDATE_EMAIL_ERROR = 'UPDATE_EMAIL_ERROR';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_ERROR = 'UPDATE_PASSWORD_ERROR';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_ERROR = 'SEND_MESSAGE_ERROR';

export const ADMIN_USER_EDIT_START = 'ADMIN_USER_EDIT_START';
export const ADMIN_USER_EDIT_STOP = 'ADMIN_USER_EDIT_STOP';
export const ADMIN_USER_SAVE = 'ADMIN_USER_SAVE';
export const ADMIN_USER_SAVE_SUCCESS = 'ADMIN_USER_SAVE_SUCCESS';
export const ADMIN_USER_SAVE_ERROR = 'ADMIN_USER_SAVE_ERROR';